version: '3.0'

expectations:
  population_size: 1000

actions:

  database_builds_html:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/database-builds.ipynb --to html --output-dir=/workspace/output
    outputs:
      moderately_sensitive:
        html: output/database-builds.html
        
  database_schema_html:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/database-schema.ipynb --to html --output-dir=/workspace/output
    outputs:
      moderately_sensitive:
        html: output/database-schema.html
        
  database_builds_md:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/database-builds.ipynb --to markdown --output-dir=/workspace/output
    outputs:
      moderately_sensitive:
        md: output/database-builds.md
        png: output/database-builds_files/*.png
        
  database_schema_md:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/database-schema.ipynb --to markdown --output-dir=/workspace/output
    outputs:
      moderately_sensitive:
        md: output/database-schema.md
        
