version: '3.0'

expectations:
  population_size: 1000

actions:

  render_database_builds:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/database-builds.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
    outputs:
      moderately_sensitive:
        cohort: output/database-builds.html
        
  render_database_schema:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/database-schema.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
    outputs:
      moderately_sensitive:
        cohort: output/database-schema.html
